content:
  # About Me Section
  - title: About Me
    layout: text
    content: |
      An architect of Container and Secret Management Platforms with extensive experience in accelerating digital transformation within major organizations. My expertise in Docker, Kubernetes, Rancher, and DevOps practices aims to industrialize software delivery pipelines efficiently. 

      I bring a deep understanding of cloud computing, CI/CD methodologies, and security & compliance to every project. My passion lies in building scalable, secure, and efficient technology solutions that drive business growth.

  # Technical Skills Section
  - title: Technical Skills
    layout: text
    content: |
      **Cloud Computing**: Proficient in AWS, Azure, and Google Cloud Platform.

      **DevOps & CI/CD**: Expertise in Jenkins, GitLab CI, and GitHub Actions.

      **Infrastructure as Code**: Advanced knowledge in HashiCorp Terraform.

      **Configuration Management**: Experienced with Ansible, Chef, and Puppet.

      **Security & Compliance**: Expert in security practices and HashiCorp Vault.

      **Monitoring & Operations**: Skilled in Prometheus, Grafana, and ELK Stack.

      **Scripting & Automation**: Proficient in Bash, Python, and PowerShell.

      **Microservices Architecture**: Knowledgeable in Docker and Kubernetes.

      **Linux System Administration**: Strong foundation in Linux administration.

  # Professional Experience Section
  - title: Professional Experience
    layout: list
    content:
      - layout: left
        title: Aqua Security
        sub_title: DevSecOps Engineer
        caption: July 2021 - December 2022
        description: |
          Leading cloud-native security solutions, focusing on application protection across the entire lifecycle. Contributed to securing supply chains, cloud infrastructure, and running workloads in diverse environments.

      - layout: left
        title: Global Logic Consulting
        sub_title: Delivery Consultant
        caption: July 2016 - July 2021
        description: |
          A digital product engineering company integrating experience design with complex engineering, facilitating clients' transition into digital businesses.
      
      - layout: left
        title: QA Consulting
        link: qa.com
        sub_title: Devops Consultants
        caption: July 2015 - July 2016
        description: |
           The QA Consulting (incorporating NETbuilder Academy) is a leading provider of Consulting Services to world leading commercial and financial institutions, as well as some of the UK’s largest Government departments.


  # Education Background Section
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of South Wales
        sub_title: BSc Computer Forensic and Security
        caption: 2011 - 2015
        description: |
          Focused on the transformation of lives through knowledge and education, preparing for the changing world of work in IT and cybersecurity.

  # Personal Interests Section
  - title: Interests
    layout: text
    content: |
      Alongside my interests in software engineering, some of my other interests and hobbies are:
      
      - Rock climbing
      - Gaming

