# Site Configuration
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content Configuration Version
version: 2

# Personal Information
name: Morgan Thomas Atkins
title: Senior Software Engineer
email: morgantatkins@mea-tech.co.uk
website: http://www.mea-tech.co.uk
darkmode: true

# Social Media Profiles
social_links:
  twitter: morgantatkins
  github: morgantatkins
  instagram: morgantatkins
  linkedin: morgantatkins
  youtube: morganatkins
  # Additional or less common profiles can be added as needed

# Extra Links with Icons
additional_links:
  - title: My Portfolio
    icon: fas fa-globe
    url: https://www.itsgoingto.be

# About Me Section
about:
  profile_image: images/my_face.jpg
  content: >
    An architect of Container and Secret Management Platforms with extensive experience in accelerating digital transformation within major organizations. Expertise in Docker, Kubernetes, Rancher, and DevOps practices, aiming to industrialize software delivery pipelines efficiently.

skills:
  - Docker Certified Associate
  - Docker Authorized Trainer
  - Docker MTA Certified
  - HashiCorp Vault
  - HashiCorp Terraform

# Professional Experience
experience:
  - title: Aqua Security
    role: DevSecOps Engineer
    duration: July 2021 - December 2022
    description: >
      Leading cloud-native security solutions, focusing on application protection across the entire lifecycle. Contributed to securing supply chains, cloud infrastructure, and running workloads in diverse environments.

  - title: Global Logic Consulting
    role: Delivery Consultant
    duration: July 2016 - July 2021
    description: >
      A digital product engineering company integrating experience design with complex engineering, facilitating clients' transition into digital businesses.

# Education Background
education:
  - institution: University of South Wales
    degree: BSc Computer Forensic and Security
    years: 2011 - 2015
    description: >
      Focused on the transformation of lives through knowledge and education, preparing for the changing world of work in IT and cybersecurity.

# Personal Interests
interests:
  - Rock climbing
  - Gaming

# Footer Configuration
footer:
  show_references: true

# Build and Plugin Settings
build:
  remote_theme: sproogen/resume-theme
  sass:
    sass_dir: _sass
    style: compressed
  plugins:
    - jekyll-seo-tag
