# Site Configuration
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content Configuration Version
version: 2

# Personal Information
name: Morgan Thomas Atkins
title: Senior Software Engineer
email: morgantatkins@mea-tech.co.uk
website: http://www.mea-tech.co.uk
darkmode: true

# Social Media Profiles
social_links:
  twitter: morgantatkins
  github: morgantatkins
  instagram: morgantatkins
  linkedin: morgantatkins
  youtube: morganatkins
  # Additional or less common profiles can be added as needed

# Extra Links with Icons
additional_links:
  - title: My Portfolio
    icon: fas fa-globe
    url: https://www.itsgoingto.be

# About Me Section
about:
  profile_image: images/my_face.jpg
  content: >
    An architect of Container and Secret Management Platforms with extensive experience in accelerating digital transformation within major organizations. Expertise in Docker, Kubernetes, Rancher, and DevOps practices, aiming to industrialize software delivery pipelines efficiently.

# Technical Skills
technical_skills:
  - category: Cloud Computing
    skills: Proficient in AWS, Azure, and Google Cloud Platform
  - category: DevOps & CI/CD
    skills: Expertise in Jenkins, GitLab CI, and GitHub Actions
  - category: Infrastructure as Code
    skills: Advanced knowledge in HashiCorp Terraform
  - category: Configuration Management
    skills: Experienced with Ansible, Chef, and Puppet
  - category: Security & Compliance
    skills: Expert in security practices and HashiCorp Vault
  - category: Monitoring & Operations
    skills: Skilled in Prometheus, Grafana, and ELK Stack
  - category: Scripting & Automation
    skills: Proficient in Bash, Python, and PowerShell
  - category: Microservices Architecture
    skills: Knowledgeable in Docker and Kubernetes
  - category: Linux System Administration
    skills: Strong foundation in Linux administration

# Professional Experience
experience:
  - title: Aqua Security
    role: DevSecOps Engineer
    duration: July 2021 - December 2022
    description: >
      Leading cloud-native security solutions, focusing on application protection across the entire lifecycle. Contributed to securing supply chains, cloud infrastructure, and running workloads in diverse environments.
  - title: Global Logic Consulting
    role: Delivery Consultant
    duration: July 2016 - July 2021
    description: >
      A digital product engineering company integrating experience design with complex engineering, facilitating clients' transition into digital businesses.

  - title: QA Consulting
    link: qa.com
    # link_text: boringcompany.com
    sub_title: DevOps Consultants
    caption: July 2015 - July 2016
    description: | # this will include new lines to allow paragraphs
       The QA Consulting (incorporating NETbuilder Academy) is a leading provider of Consulting Services to world leading commercial and financial institutions, as well as some of the UK’s largest Government departments.

# Education Background
education:
  - institution: University of South Wales
    degree: BSc Computer Forensic and Security
    years: 2011 - 2015
    description: >
      Focused on the transformation of lives through knowledge and education, preparing for the changing world of work in IT and cybersecurity.

# Personal Interests
interests:
  - Rock climbing
  - Gaming

# Footer Configuration
footer:
  show_references: true

# Build and Plugin Settings
build:
  remote_theme: sproogen/resume-theme
  sass:
    sass_dir: _sass
    style: compressed
  plugins:
    - jekyll-seo-tag
