# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Morgan Thomas Atkins
title: Senior Software Engineer
email: morgantatkins@hotmail.com
website: mea-tech.co.uk

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: morgantatkins
github_username: morgantatkins
instagram_username: morgantatkins
linkedin_username: morgantatkins
youtube_username: morganatkins

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be

# About Section
about_profile_image: images/my_face.jpg
about_content: |
  An architect of Container and Secret Management Platforms used to Accelerate Digital Transformation within FTSE 100 & 500 Organisations. Container expertise includes Docker, Kubernetes, Rancher. Complementing my Container experience, I also have extensive 'DevOps', Continuous Integration, and Continuous Delivery experience after working with dozens of organisations to jump-start, accelerate, and industrialise Software Delivery Pipelines. I am most skilled in: Docker Certified Associate | Docker Authorised Trainer | Docker MTA Certified | Hashicorp Vault | Hashicorp Terraform.

content:
  - title: Technical Skills
    layout: text
    content: |
      **Cloud Computing**: Proficient in AWS, Azure, and Google Cloud Platform.
      
      **DevOps & CI/CD**: Expertise in Jenkins, GitLab CI, and GitHub Actions.
      
      **Infrastructure as Code**: Advanced knowledge in HashiCorp Terraform.
      
      **Configuration Management**: Experienced with Ansible, Chef, and Puppet.
      
      **Security & Compliance**: Expert in security practices and HashiCorp Vault.
      
      **Monitoring & Operations**: Skilled in Prometheus, Grafana, and ELK Stack.
      
      **Scripting & Automation**: Proficient in Bash, Python, and PowerShell.
      
      **Microservices Architecture**: Knowledgeable in Docker and Kubernetes.
      
      **Linux System Administration**: Strong foundation in Linux administration.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Super awesome project
        link: https://github.com/morgantatkins
        quote: "If You're Not Embarrassed By The First Version Of Your Product, You’ve Launched Too Late"

  - title: Experience
    layout: list
    content:
      - layout: left
        title: ECS
        link: https://ecs.co.uk
        sub_title: Delivery Consultants
        caption: July 2016 - Present
        quote: "Solving 21st century problems by digging holes and making game-changing products like the *not a flamethrower*"
        description: |
          Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard, and I play my part in making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: QA Consulting
        link: https://qa.com
        sub_title: DevOps Consultants
        caption: July 2015 - July 2016

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of South Wales
        caption: 2011 - 2015
        sub_title: BSc Computer Forensic and Security

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in software engineering, some of my other interests and hobbies are:
      - Rock climbing
      - Gaming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 
