# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Morgan Thomas Atkins
title: Cloud Engineering Evangelist
email: morgan.atkins@mea-tech.co.uk
website: mea-tech.co.uk

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: morgantatkins
instagram_username: morgantatkins
linkedin_username: morgantatkins
youtube_username: morganatkins

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be

# About Section
about_profile_image: images/IMG_6274.png
about_content: |
    Hello, I'm Morgan Thomas Atkins, a dedicated Cloud Engineering Evangelist with a deep-seated passion for guiding enterprises through their digital transformation journeys. My expertise lies at the intersection of cloud computing, containerization, and DevOps practices, where I excel in architecting Container and Secret Management Platforms that propel organizations into the future.

    Certified in Docker and with extensive experience in Kubernetes and Rancher, I have a proven track record of designing and deploying scalable, secure, and resilient infrastructure solutions that streamline operations and foster innovation. My skills with HashiCorp Vault and Terraform further empower me to ensure that these solutions are not only efficient but also secure and compliant with the highest industry standards.
    
    My role goes beyond the technical; as an evangelist, I thrive on sharing knowledge, best practices, and the transformative potential of cloud engineering. Through workshops, seminars, and one-on-one mentoring, I've inspired teams and organizations to embrace cloud technologies, thereby accelerating their digital transformation initiatives.
    
    I believe in the power of collaboration and the importance of fostering a culture where continuous learning, innovation, and improvement are part of the daily routine. By bridging the gap between technical possibilities and business objectives, I help organizations leverage cloud technology to achieve their strategic goals.
    
    My commitment to the cloud engineering community is driven by a desire to see others succeed. Whether it's through leading edge solutions, thought leadership, or hands-on guidance, I am dedicated to empowering professionals and organizations to unlock the full potential of cloud computing.

content:
  - title: Skills
    layout: list
    content:
      - layout: top-middle
        quote: 
          
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Super awesome project
        link: https://github.com/morgantatkins
        quote: "If You're Not Embarrassed By The First Version Of Your Product, You’ve Launched Too Late"

  - title: Experience
    layout: list
    content:
      - layout: left
        title: WALT Labs
        sub_title: Head of Engineering, EMEA
        caption: January 2023 - Present
        description: |

      - layout: left
        title: Aqua Security
        sub_title: DevSecOps Engineer
        caption: July 2021 - December 2022
        description: |
          Leading cloud-native security solutions, focusing on application protection across the entire lifecycle. Contributed to securing supply chains, cloud infrastructure, and running workloads in diverse environments.

      - layout: left
        title: Global Logic Consulting ( Formally ECS )
        sub_title: Delivery Consultant
        caption: July 2016 - July 2021
        description: |
          A digital product engineering company integrating experience design with complex engineering, facilitating clients' transition into digital businesses.

      - layout: left
        title: QA Consulting
        link: https://qa.com
        sub_title: DevOps Consultants
        caption: July 2015 - July 2016

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of South Wales
        caption: 2011 - 2015
        sub_title: BSc Hons Computer Forensic and Security

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in software engineering, some of my other interests and hobbies are:

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 
